version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0.3
jobs:
  bundle_lint_test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.5.23
      rails_version:
        type: string
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout
      - run:
          name: Check for 'master' branch
          command: |
              git fetch --all --quiet --prune --prune-tags
              if [[ -n "$(git branch --all --list master */master)" ]]; then
                  echo "A branch named 'master' was found. Please remove it."
                  echo "$(git branch --all --list master */master)"
              fi
              [[ -z "$(git branch --all --list master */master)" ]]

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - run:
          name: Generate test app and work around zeitwerk issue with engine_cart
          command: |
            bundle exec rake engine_cart:generate || true
            bundle install
            cd .internal_test_app
            bundle install
            sed -i "s/assets tasks/assets tasks generators/" config/application.rb
            bundle exec rails g test_app

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_lint_test:
          name: ruby3-4_rails8-0
          ruby_version: 3.4.4
          rails_version: 8.0.2
      - bundle_lint_test:
          name: ruby3-3_rails7-2
          ruby_version: 3.3.4
          rails_version: 7.2.0
      - bundle_lint_test:
          name: ruby3-2_rails7-2
          ruby_version: 3.2.5
          rails_version: 7.2.0
      - bundle_lint_test:
          name: ruby3-2_rails7-1
          ruby_version: 3.2.5
          rails_version: 7.1.3.4
